# 10단원 핵심정리

넘파이는 리스트가 아니라 배열로 다차원 데이터를 다룬다.  
배열은 동일한 자료형을 연속해서 가진 데이터 구조로 읽고 쓰는 일을 빠르게 할 수 있다.  
리스트와 달리 넘파이 배열들을 서로 연산하면 벡터와 행렬처럼 다루어진다.  
넘파이 배열도 리스트와 다른 반복가능 객체처럼 슬라이싱을 적용할 수 있다.  
넘파이는 넘파이만의 스타일로 슬라이싱을 할 수 있으며, 리스트 등과 다른 방식의 결과가 나온다.  
슬라이싱과 별개로 논리적 조건을 부여하여 항목을 가져오는 일도 가능하다.  

# 심화문제풀이  

## 1.

In [6]:
import numpy as np
num_arr=np.array(range(1,21)) # num_arr=np.arange(1,21)
print(num_arr)
print(num_arr[-1::-1])
print("num_arr 내의 모든 원소의 합: ",num_arr.sum(axis=0))  #print(num_arr[::-1]) #num_arr.sum() or num_arr.sum(num_arr)
print(num_arr.reshape(5,4))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1]
num_arr 내의 모든 원소의 합:  210
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


## 2.

In [13]:
n = np.array(range(25))
n_arr=n.reshape(5,-1) #n_arr=n.reshape(5,5)
n_arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [16]:
print("첫 원소 : ",n_arr[0,0])
print("마지막 원소 : ",n_arr[-1,-1])

첫 원소 :  0
마지막 원소 :  24


In [24]:
n_arr[:2,:] # n_arr[:2]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [25]:
n_arr[2:,:]# n_arr[2:]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [26]:
n_arr[:,0::2]

array([[ 0,  2,  4],
       [ 5,  7,  9],
       [10, 12, 14],
       [15, 17, 19],
       [20, 22, 24]])

In [27]:
n_arr[0::2,0::2]

array([[ 0,  2,  4],
       [10, 12, 14],
       [20, 22, 24]])

In [28]:
n_arr[:2,:].reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

## 3.

In [19]:
a=np.random.rand(3,3,3)
a 

array([[[0.73046572, 0.02634488, 0.39917172],
        [0.60303311, 0.21501511, 0.74756583],
        [0.86719133, 0.47719832, 0.40635305]],

       [[0.15827718, 0.14045152, 0.02313664],
        [0.20503655, 0.67189305, 0.08689841],
        [0.1178483 , 0.9565623 , 0.77797491]],

       [[0.60606443, 0.57862247, 0.86279012],
        [0.55689884, 0.3957553 , 0.10590149],
        [0.3750773 , 0.25900385, 0.20375412]]])

In [33]:
print("a의 원소들 중 최댓값 : ",a.max())

a의 원소들 중 최댓값 :  0.95106467987996


In [34]:
print("a의 원소들 중 최댓값의 위치: ",a.argmax())

a의 원소들 중 최댓값의 위치:  15


## 4.

In [8]:
c=np.array([1,0]*13)
d=c[:-1]
e=d.reshape(5,5)
e

array([[1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1]])

In [25]:
A = np.ones(25, dtype=int)
A[1::2] = 0
A

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1])

In [28]:
A= np.zeros(25 , dtype=int)
A

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0])

In [32]:
A=np.array([i%2 for i in range(1,26)])
A

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1])

In [12]:
print(f"행렬의 행 방향 성분의 합 : {e.sum(axis = 0)}") # 행 = 세로 ,열 = 가로

행렬의 행 방향 성분의 합 : [3 2 3 2 3]


## 5.

In [36]:
a= np.arange(0,32).reshape(4,4,2)

print("10번째 원소 : ",a.flatten()[9])
print("20번째 원소 : ",a.flatten()[19])# a.reshape[-1][19]

10번째 원소 :  9
20번째 원소 :  19


## 6.

In [36]:
x1=[i for i in range(100)]
x2=[i + np.random.randint(1,10) for i in range(100)]
x3=[i + np.random.randint(1,50) for i in range(100)]
x4=[np.random.randint(1,100) for i in range(100)]
corr=np.corrcoef([x1,x2,x3,x4])
print(corr)

[[ 1.          0.99566589  0.9063786  -0.11193341]
 [ 0.99566589  1.          0.90801123 -0.11184749]
 [ 0.9063786   0.90801123  1.         -0.13255714]
 [-0.11193341 -0.11184749 -0.13255714  1.        ]]


In [42]:
x1=np.arange(100)
x2=x1+np.random.randint(1,10,size=(100,))
x3=x1+np.random.randint(1,50,size=(100,))
x4=np.random.randint(1,100,size=(100,))

print(np.corrcoef([x1,x2,x3,x4]))
np.corrcoef(x1,x2)

[[ 1.          0.99608017  0.90828174 -0.0056526 ]
 [ 0.99608017  1.          0.90877723 -0.01348598]
 [ 0.90828174  0.90877723  1.          0.05287657]
 [-0.0056526  -0.01348598  0.05287657  1.        ]]


array([[1.        , 0.99608017],
       [0.99608017, 1.        ]])

1) x1 과 가장 상관관계가 높은 리스트:x2  
2) x1 과 가장 상관관계가 낮은 리스트:x4